/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listas;

/**
 *
 * @author aluno
 */
public class LSDialog extends javax.swing.JDialog {
    private ListaSeq lista;
    private final int TAM_MAX = 15;
    private java.awt.Frame parent;
    /**
     * Creates new form LSDialog
     */
    public LSDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.setTitle("Lista Sequencial");
        this.setLocationRelativeTo(parent);
        
       
        criarLista();

        this.setVisible(true);
        
        
       
    }
    
    private void criarLista() {
        listPanel.removeAll();
         this.lista = new ListaSeq(this.TAM_MAX);
        for(int i = 0; i < this.TAM_MAX; i++) {   
            // SeqElement el = new SeqElement(i+1, -1);
            // listPanel.add(el);
        }
        listPanel.repaint();
        listPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        inserirLabel = new javax.swing.JLabel();
        insPosField = new javax.swing.JTextField();
        insValorField = new javax.swing.JTextField();
        inserirButton = new javax.swing.JButton();
        pesValorLabel = new javax.swing.JLabel();
        pesValorField = new javax.swing.JTextField();
        pesValorButton = new javax.swing.JToggleButton();
        pesPosLabel = new javax.swing.JLabel();
        pesPosField = new javax.swing.JTextField();
        pesPosButton = new javax.swing.JToggleButton();
        removeLabel = new javax.swing.JLabel();
        removeField = new javax.swing.JTextField();
        removeButton = new javax.swing.JToggleButton();
        exitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        inserirLabel.setText("Inserir Elemento");

        insPosField.setText("Posição");

        insValorField.setText("Valor");

        inserirButton.setText("Inserir Elemento");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirButtonActionPerformed(evt);
            }
        });

        pesValorLabel.setText("Pesquisar Por Valor");

        pesValorField.setText("Valor");

        pesValorButton.setText("Pesquisar");
        pesValorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesValorButtonActionPerformed(evt);
            }
        });

        pesPosLabel.setText("Pesquisar Por Posição");

        pesPosField.setText("Posição");
        pesPosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesPosFieldActionPerformed(evt);
            }
        });

        pesPosButton.setText("Pesquisar");
        pesPosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesPosButtonActionPerformed(evt);
            }
        });

        removeLabel.setText("Remover");

        removeField.setText("Posição");

        removeButton.setText("Remover");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Fechar");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Resetar");
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insValorField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(insPosField)
                    .addComponent(inserirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(inserirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesValorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesValorField)
                    .addComponent(pesValorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesPosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pesPosField)
                    .addComponent(pesPosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeField)
                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inserirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insPosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insValorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inserirButton)
                .addGap(18, 18, 18)
                .addComponent(pesValorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesValorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesValorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesPosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesPosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesPosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesPosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesPosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesPosFieldActionPerformed

    private void updateList() {
        listPanel.removeAll();
       for(int i = 0; i < this.TAM_MAX; i++) {
           int value = this.lista.elemento(i+1);
           SeqElement el = new SeqElement(i+1, this.lista.elemento(i+1));

           if(value >= 0) {
               listPanel.add(el);
           }
            
       }
       listPanel.repaint();
       listPanel.revalidate();
        //System.out.println("FOI BUCETUDA");
    }
    
    private void inserirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirButtonActionPerformed
       /* VAI INSERIR ELEMENTO */
       String posString = insPosField.getText();
       String valorString = insValorField.getText();
       
       /* TODO USAR TRY CATCH*/
       int valor = Integer.parseInt(valorString);
       if(valor > 0) {
           int pos = Integer.parseInt(posString);
        
       this.lista.insere(pos, valor);
       updateList();
       }
       
        
    }//GEN-LAST:event_inserirButtonActionPerformed

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetButtonMouseClicked

        criarLista();
    }//GEN-LAST:event_resetButtonMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void pesValorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesValorButtonActionPerformed
    
        String posString = pesValorField.getText();
        int pos= Integer.parseInt(posString);
        
        int resultado = this.lista.posicao(pos);
        
        TelaPesquisaV newtela = new TelaPesquisaV(this.parent, true, resultado);
           
       
        
        
    }//GEN-LAST:event_pesValorButtonActionPerformed

    private void pesPosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesPosButtonActionPerformed
        // TODO add your handling code here:
        String posString = pesPosField.getText();
        int pos = Integer.parseInt(posString);
        
        int resultado = this.lista.elemento(pos);
        
        TelaPesquisaPos tela = new TelaPesquisaPos(this.parent, true, resultado);
        
    }//GEN-LAST:event_pesPosButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        
        String removeString = removeField.getText();
        int removePos = Integer.parseInt(removeString);
        
        int resultado = this.lista.remove(removePos);
        
        if(resultado > 0) {
            System.out.println("DADO: " + resultado);
        }
        updateList();
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LSDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LSDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LSDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LSDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LSDialog dialog = new LSDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField insPosField;
    private javax.swing.JTextField insValorField;
    private javax.swing.JButton inserirButton;
    private javax.swing.JLabel inserirLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JToggleButton pesPosButton;
    private javax.swing.JTextField pesPosField;
    private javax.swing.JLabel pesPosLabel;
    private javax.swing.JToggleButton pesValorButton;
    private javax.swing.JTextField pesValorField;
    private javax.swing.JLabel pesValorLabel;
    private javax.swing.JToggleButton removeButton;
    private javax.swing.JTextField removeField;
    private javax.swing.JLabel removeLabel;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
