/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listas;

/**
 *
 * @author Iara
 */
public class TelaPesquisaV extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaV
     */
    public TelaPesquisaV(java.awt.Frame parent, boolean modal, int resultado ) {
        super(parent, modal);   
        initComponents();
        if (resultado > 0 ){
            lblPesquisaV.setText("Posição:" + resultado);
        }
        
        else{
            lblPesquisaV.setText("Valor não encontrado");
        }
        
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaPesquisaV = new javax.swing.JPanel();
        lblPesquisaV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPesquisaV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPesquisaV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlTelaPesquisaVLayout = new javax.swing.GroupLayout(pnlTelaPesquisaV);
        pnlTelaPesquisaV.setLayout(pnlTelaPesquisaVLayout);
        pnlTelaPesquisaVLayout.setHorizontalGroup(
            pnlTelaPesquisaVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPesquisaV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        pnlTelaPesquisaVLayout.setVerticalGroup(
            pnlTelaPesquisaVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaPesquisaVLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPesquisaV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaPesquisaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaPesquisaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPesquisaV;
    private javax.swing.JPanel pnlTelaPesquisaV;
    // End of variables declaration//GEN-END:variables
}
